### ISSUE TITLE
only one category appears : Remix - meta gem

### ISSUE THREAD

**Issue by vince2paname** [Krealle/BetterBags_RemixGems#1]
Hello,
I have just installed the addon.
I can see on your screenshot that there are a category for each type of gem.
But for me, all the gems stays in one category only : Remix - meta gem.

![image](https://github.com/Krealle/BetterBags_RemixGems/assets/103256765/e787a478-e48b-4b7b-bb3d-fb5b538a2be1)

**Comment by Krealle** [comment]
Hello, thanks for reporting it! It was a localization problem, have just pushed out a new update that resolves this issue.
